require('dotenv').config();
require('./config/database');

// const Category = require('./models/category');
const Product = require('./models/product');
const Category = require('./models/category');

// Pattern: 
//Immediately Invoked function expression

(async function() {

await Category.deleteMany({});
    const categories = await Category.create([
      {name: '$0-20', sortOrder: 10},
      {name: '$20-30', sortOrder: 20},
      {name: '$30-40', sortOrder: 30},
      {name: '$40-50', sortOrder: 40},
      {name: '$50-60', sortOrder: 50},
      {name: '$60-70', sortOrder: 60},
      {name: '$70-80', sortOrder: 70},
    ]);

  await Product.deleteMany({});
 const products = await Product.create([
    {name: 'Hopeless Romantic', 
        description:'This painting print has a bold mix of playful hues for an eye-catching focal point in any modern room. Originally by artist Amira Rahim, this recreation of "Hopeless Romantic" is printed with crisp, quality inks on wrapped canvas for a gallery-worth look. The square image offers a swirling abstract collision of colors, including yellow, pink, orange, and blue. We love that this wall art comes with mounting hardware, so it\'s ready to hang and inspire right out of the box. Size: 36" H x 36" W', 
        image: "../public/art1.png",
        category: categories[0],
        price: 15.95},
    {name: 'French Macarons by Amira Rahim', 
        description:'Our canvases are certified museum-grade and designed to withstand the test of time. Durability, image clarity, and color accuracy are our top priorities, as we use archival inks to prevent fading and to preserve as much fine detail as possible with no over-saturation or color shifting. Featuring a proprietary design, these canvases produce the tightest corners without any bubbles, ripples, or bumps, and will not warp or sag over time. Additionally, our canvases include a finished backing with pre-installed hanging hardware that adds an extra level of style. Choose with or without a floating frame to achieve your desired look. This giclee wall art is sure to become the focal piece of your living room, family room, great room, bedroom, bathroom, office, kitchen, dining room, game room, bar, or more!' , 
        image: "../public/art2.png",
        category: categories[0],
        price: 13.99},
    {name: 'Pink And Gold Abstract - Wrapped Canvas Painting', 
        description:'This abstract art print showcases overlapping bands of glittering, colorful hues for a glam and artful look on your walls. Designed in the USA, this giclee artwork, entitled "Pink and Gold Abstract," is wrapped around the canvas with a solid matboard backing. The UV- and fade-resistant archival inks are ideal for hanging in a sunny spot in your living room or bedroom. We love that this print comes in a variety of sizes to choose from that best suit your space. Plus, it comes with wall-mounting hardware, saving you an extra trip to the store.' , 
        image: "../public/art3.png",
        category: categories[0],
        price: 8.99},
    {name: 'Sprinkled Flowers by Silvia Vassileva - Wrapped Canvas Painting', 
        description:'This painting print brightens any space with its botanical theme and summery palette. Originally a watercolor painting by Silvia Vassileva, "Sprinkled Flowers" is printed on a rectangular wrapped canvas. The horizontal print depicts a grassy field brimming with blooming flowers in pink, yellow, and green hues. Plus, its abstract background features muted, multi-color brushstrokes for a painterly look and whimsical feel. This frameless canvas comes in multiple sizes to suit your space, and it complements decor styles from traditional to modern farmhouses.',
        image: "../public/art4.png",
        category: categories[1],
        price: 28.99},
    {name: 'Abstract Colorful Spring Flowers - Painting on Canvas', 
        description:'This beautiful `Abstract Colorful Spring Flowers` fine art giclee canvas print is printed on premium quality canvas, using the finest quality inks which will not fade over time. Each giclee print is stretched tightly over a 1-inch wood subframe ensuring the canvas is taught and does not buckle. The canvas print is inserted into the wood floating frame for Floater Framed Art which is available in several frame colors. All of our wall art is carefully packaged with corner protection, fragile labeling, and sturdy boxes to ensure safe delivery. Every art arrives ready to hang on the wall, with the hanging kits included.',
        image: "../public/art5.png",
        category: categories[1],
        price: 25.99},
    {name: 'Sunset Painting With Colorful Reflections II - Painting on Canvas', 
        description:'This beautiful `Sunset with Colorful Reflections II` fine art giclee canvas print is printed on premium quality canvas, using the finest quality inks which will not fade over time. Each giclee print is stretched tightly over a 1-inch wood sub frame ensuring the canvas is taught and does not buckle. The canvas print is inserted into the wood floating frame for Floater Framed Art. All of our wall art is carefully packaged with corner protection, fragile labeling, and sturdy boxes to ensure safe delivery. Every art arrives ready to hang on the wall, with the hanging kits included.' , 
        image: "../public/art6.png",
        category: categories[1],
        price: 28.95},
    {name: 'Bright Bouquet Of Spring Flowers On Purple Background - Painting on Canvas', 
        description:'Enliven your space with this graphic art print\'s vivid hues and floral composition. The design features a bouquet of flowers set in a vase, surrounded by an almost galactic purple background. It\'s premium giclee-printed with high-quality inks on wrapped canvas, with a bold color palette that shows off purple, blue, and yellow blooms. We love that this dynamic wall art comes with mounting hardware, so it\'s ready to hang right out of the box. Best of all, it comes with a range of frame options.' , 
        image: "../public/art7.png",
        category: categories[2],
        price: 34.99},
    {name: 'Tyrion Gouache Sapphire On Gray VI - Painting on Canvas', 
        description:'This beautiful art is printed using the highest quality fade-resistant ink on canvas. Every one of our fine art giclee canvas prints is printed on premium quality canvas, using the finest quality inks which will not fade over time. Each giclee print is stretched tightly over a 1-inch wood subframe for small-size prints or a 1.5-inch wood subframe for large-size prints ensuring the canvas is taught and does not buckle. This framed art print is available in many different color frames. All of our wrapped/framed canvas prints are carefully packaged with corner protectors, fragile labeling, and sturdy boxes to ensure safe delivery. Every wrapped/framed canvas print arrives ready to hang on the wall, with the hanging kits included.' , 
        image: "../public/art8.png",
        category: categories[2],
        price: 35.95},
    {name: 'Colorful Spot - Wrapped Canvas Print', 
        description:'Providing a pop of color and a splash of springtime style, this oil painting print is a lovely focal point for any room in your home. This design showcases seven bright birds sitting in a row atop a branch up against a white background. Printed in the USA, this giclee canvas is wrapped over wooden stretcher bars. Wall mounting hardware is included, so it\'s ready to hang as soon as it reaches your door.' , 
        image: "../public/art9.png",
        category: categories[3],
        price: 41.95},
    {name: 'Treeline by Katrina Pete - Wrapped Canvas Painting', 
        description:'This wall print features misty tree lines and birds gently flying on the top that\'s right at home in your industrial-inspired loft or home office. It\'s made in the USA, and it\'s printed on canvas with a wrapped frame. The green, blue, and white color palettes form a natural nature scene that freshens up any modern space. It also uses UV- and fade-resistant inks that stand up to direct sunlight. Plus, this rectangular wall print comes in a variety of sizes to choose from that best suits your space.' , 
        image: "../public/art10.png",
        category: categories[3],
        price: 42.95},
    {name: 'Abstract IX by Salvatore Principe - Wrapped Canvas', 
        description:'An ambiguous object lies at the core of Abstract IX. Spatters of vibrant color peek through from under a coating of murky white smears, vaguely revealing curvaceous shapes. Strategically placed lines allude to the organic nature of the subject and distract the eye with sporadic movement. Gaze into this hazy art piece as you formulate your understanding of the artist’s intent. Place this piece among modern designs to stylize your home’s décor. Handcrafted in the United States, this gallery-wrapped canvas art arrives ready to hang on your wall.' , 
        image: "../public/art11.png",
        category: categories[3],
        price: 43.95},
    {name: 'Ocean Eye I by Danita Delimont - Wrapped Canvas Print', 
        description:'This painting print features a nature subject in various shades of blue, yellow, black, and gray. Made in the USA and designed by Danita Delimont, this giclee canvas print depicts a forested shoreline landscape at dawn or dusk, with mountains in the background and fog hovering over the water\'s surface. This rustic, lodge-worthy piece uses watercolors, and the canvas wraps around a wood frame in multiple size options. One wall hook is included, so you\'re able to hang up this print right when it arrives.' , 
        image: "../public/art12.png",
        category: categories[4],
        price: 51.95},
    {name: 'Captive Color I - Wrapped Canvas Print', 
        description:'This bright artwork brings abstract style and bold color to your living room, office, or hallway. Titled "Captive Color I," this piece features an array of long stripes of bright blues, oranges, and reds that stand out and coordinate to create a dynamic piece. We love how this art\'s asymmetrical edges add a subtle geometric feel to your walls. This artwork is printed on wrapped canvas using giclee archival inks. Best of all, it comes with a wall hook that makes it easy to install on your walls.' , 
        image: "../public/art13.png",
        category: categories[4],
        price: 52.95},
    {name: 'Eli Octopus In The Deep Blue Sea by Eli Halpin - Wrapped Canvas Print', 
        description:'Wave goodbye to a plain entryway and welcome coastal flair into your abode with this crisp painting print. Made in the United States, this gallery-worthy poly-cotton canvas instantly adds eye-catching appeal to any foyer. This dynamic design showcases an octopus swimming in the depths of the navy blue sea, complete with multicolored suction cups and sprawling arms that are sure to grip guests\' attention as soon as they walk through the door. Hang it over a distressed white console table to start a shoreline-inspired ensemble, then roll out a natural jute area rug to ensure your room is awash with charm from top to bottom.' , 
        image: "../public/art14.png",
        category: categories[5],
        price: 64.95},
    {name: 'Miko Starry Night over the Rhone by Vincent Van Gogh Painting on Canvas', 
        description:'In 1888, Vincent van Gogh lived in the city of Arles in Southern France, where he found inspiration for many of his most famous paintings in the Provençal landscape and charming city streets. During this time, van Gogh painted “Starry Night Over The Rhone”, one of his most famous paintings. Now hanging in the Musee D’Orsay, you can add this legacy to your home with this reproduction. This piece showcases a glowing city and starry sky whose lights are reflected in the calm waters of the river Rhone.' , 
        image: "../public/art15.png",
        category: categories[5],
        price: 65.95},
    {name: 'Irises by Vincent Van Gogh - Wrapped Canvas Painting', 
        description:'Awash in warm colors and heavy brushstrokes, this brilliant painting print of Vincent van Gogh’s famous “Irises” depicts a field of flowers in a soft spring breeze. Made in North America, this impressionist design is printed on cotton canvas, which is wrapped over solid wood bars. The tones can brighten up any wall, and it arrives ready to hang so you can get the right to decorate.' , 
        image: "../public/art16.png",
        category: categories[5],
        price: 66.95},
    {name: 'Thrill Seeker - Graphic Art on Canvas', 
        description:'Will adorn your wall with this stunning wall art. Display this adorable decor in your living area. Add a faux focus and a colorful area rug to bring the room together. Hang this artwork in the master suite. Add some vibrant throw pillows and a playful blanket for a fashionable new decor theme.' ,
        image: "../public/art17.png",
        category: categories[5],
        price: 67.95},
    {name: 'Sun Tipped Tropicals - 3 Piece Wrapped Canvas Print', 
        description:'Sun-tipped tropicals- premium gallery-wrapped canvas - ready to hang a premium hand-stretched gallery-wrapped canvas print created to last. Featuring a beveled solid wood stretcher bar, each piece comes ready to hand in 6 sizes available. Each piece is made to order. Built to last. Each piece comes ready to hang. Solid wood stretcher. Fade and water-resistant. Made domestically.' , 
        image: "../public/art18.png",
        category: categories[6],
        price: 71.95},
    {name: 'Paris - Wrapped Canvas Print', 
        description:'Add tres chic style to any space with this distinctive wrapped canvas art. This rectangular piece features the Eiffel tower in the background of a rainy Parisian street scene, rendered in an impressionistic style in hues of gray, white, red, and black. This vintage-inspired artwork is printed on poly-cotton matte canvas and stretched over a polystyrene frame. It mounts horizontally and is easy to hang over your couch, bed, or dining table.' ,  
        image: "../public/art19.png",
        category: categories[6],
        price: 74.95},
    {name: 'Behind The Mountains by Susana Limon - Wrapped Canvas Print', 
        description:'Enliven your walls with this wrapped canvas landscape painting. Titled "Behind The Mountains," this art was originally by Susana Limon and features a scenic painting of mountains and sky in shades of blue and green. Made in the USA, this piece is printed on canvas and originally painted in soft watercolors for a fresh appearance. We love that this piece has a landscape orientation that\'s right at home over your console table or home office desk. Best of all, it comes with two wall hooks for easy installation.' , 
        image: "../public/art20.png",
        category: categories[6],
        price: 75.95},
    {name: 'Beach Driftwood - Wrapped Canvas Print', 
        description:'Bring a touch of serene style to your space with this distinctive giclee print. Entitled “Beach Driftwood,” this rectangular photograph is printed on cotton canvas and hand-stretched over a solid wood frame. It depicts a beach landscape with seagrass, sand, and rolling waves, in shades of beige, blue, green, and white. It includes mounting hardware, so it’s easy to hang horizontally. This piece creates a focal point over a sofa, bed, or dining room table in your coastal home.' ,  
        image: "../public/art21.png",
        category: categories[6],
        price: 76.95},
    {name: 'Japanese Bridge by Claude Monet Painting on Canvas', 
        description:'Take any empty entryway wall or spare space over the sofa and turn it into a museum-worthy display with this eye-catching canvas print. Showcasing a reproduction of Claude Monet\'s "Japanese Bridge", which was painted in 1899, it offers a dreamy waterside scene with pastel hues of purple, blue, and green. This piece is giclee-printed on canvas and wrapped around a rectangular frame for a look that rivals any artful accent.' , 
        image: "../public/art22.png",
        category: categories[6],
        price: 77.95}
  ]);

  console.log(products)

  process.exit();

})();