require('dotenv').config();
require('./config/database');

// const Category = require('./models/category');
const Product = require('./models/product');
const Category = require('./models/category');

// Pattern: 
//Immediately Invoked function expression

(async function() {

await Category.deleteMany({});
    const categories = await Category.create([
      {name: '$10-20', sortOrder: 10},
      {name: '$20-30', sortOrder: 20},
      {name: '$30-40', sortOrder: 30},
      {name: '$40-50', sortOrder: 40},
      {name: '$50-60', sortOrder: 50},
      {name: '$60-70', sortOrder: 60},
      {name: '$70-80', sortOrder: 70},
    ]);

  await Product.deleteMany({});
 const products = await Product.create([
    {name: 'Hamburger', 
        description:'this is the description of the painting', 
        image: "../public/art1.png",
        category: categories[0],
        price: 10.95},
    {name: 'Turkey Sandwich', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[0],
        price: 13.95},
    {name: 'Hot Dog', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[0],
        price: 17.95},
    {name: 'Crab Plate', 
        description:'this is the description of the painting',
        image: "../public/art1.png",
        category: categories[1],
        price: 21.95},
    {name: 'Fried Shrimp', 
        description:'this is the description of the painting',
        image: "../public/art1.png",
        category: categories[1],
        price: 22.95},
    {name: 'Whole Lobster', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[1],
        price: 28.95},
    {name: 'Taco', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[2],
        price: 34.95},
    {name: 'Burrito', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[2],
        price: 35.95},
    {name: 'Pizza Slice', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[3],
        price: 41.95},
    {name: 'Spaghetti', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[3],
        price: 42.95},
    {name: 'Garlic Bread', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[3],
        price: 43.95},
    {name: 'French Fries', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[4],
        price: 51.95},
    {name: 'Green Salad', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[4],
        price: 52.95},
    {name: 'Ice Cream', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[5],
        price: 64.95},
    {name: 'Cup Cake', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[5],
        price: 65.95},
    {name: 'Custard', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[5],
        price: 66.95},
    {name: 'Strawberry Shortcake', 
        description:'this is the description of the painting' ,
        image: "../public/art1.png",
        category: categories[5],
        price: 67.95},
    {name: 'Milk', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[6],
        price: 71.95},
    {name: 'Coffee', 
        description:'this is the description of the painting' ,  
        image: "../public/art1.png",
        category: categories[6],
        price: 74.95},
    {name: 'Mai Tai', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[6],
        price: 75.95},
    {name: 'Beer', 
        description:'this is the description of the painting' ,  
        image: "../public/art1.png",
        category: categories[6],
        price: 76.95},
    {name: 'Wine', 
        description:'this is the description of the painting' , 
        image: "../public/art1.png",
        category: categories[6],
        price: 77.95}
  ]);

  console.log(products)

  process.exit();

})();